### ISSUE TITLE
[Feature Request] chance.falsy()

### ISSUE THREAD

**Issue by evonsdesigns** [chancejs/chancejs#360] opened 2018-04-24 13:45 UTC
Returns any of the following [falsy values](https://developer.mozilla.org/en-US/docs/Glossary/Falsy):

* false
* null
* undefined
* 0
* NaN
* ''

**Comment by hugoiuri** [comment] 2018-08-03 14:20
I created a pull request (#378) to solve this feature request.

**Comment by emahuni** [comment] 2021-02-28 05:48
can you please put an alias to it, 'falsey'

**Comment by emahuni** [comment] 2021-02-28 05:49
also I noticed that if you use the pool parameter it doesn't work as intended

**Comment by emahuni** [comment] 2021-02-28 05:50
oh and close this issue

**Closed** 2021-11-23 15:15 UTC
